version: '3.9'

services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: nestjs-easy-auth-mongo
    ports:
      - 27017:27017
    volumes:
      - nestjs_easy_auth_mongo_data_container:/data/db

volumes:
  nestjs_easy_auth_mongo_data_container:
